# Question 8 – Imbalanced Pima Diabetes Data
Dataset: `pima-diabetes.xlsx`.

In [3]:
import os
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix

def load_pima():
    for p in [
        'pima-diabetes.xlsx', 'pima_diabetes.xlsx',
        '/mnt/data/pima-diabetes.xlsx', '/mnt/data/pima_diabetes.xlsx'
    ]:
        if os.path.exists(p):
            path = p
            break
    else:
        raise FileNotFoundError('pima-diabetes.xlsx not found')

    df = pd.read_excel(path)

    # Normalize Outcome and map strings to 0/1
    outcome_cols = [c for c in df.columns if c.strip().lower() == 'outcome']
    if outcome_cols:
        oc = outcome_cols[0]
        if oc != 'Outcome':
            df = df.rename(columns={oc: 'Outcome'})

    df['Outcome'] = (
        df['Outcome']
        .astype(str)
        .str.strip()
        .map({'Non-Diabetic': 0, 'Diabetic': 1})
    )

    return df

pima = load_pima()
print("Outcome value counts (after mapping):")
print(pima['Outcome'].value_counts(dropna=False))

# For modeling: drop rows with missing Outcome only
model_df = pima.dropna(subset=['Outcome']).copy()

X = model_df.drop(columns=['Outcome'])
y = model_df['Outcome']

# Impute features column-wise (median) – no listwise deletion
X_imputed = X.copy()
for col in X_imputed.columns:
    med = X_imputed[col].median(skipna=True)
    X_imputed[col] = X_imputed[col].fillna(med)

X_train, X_test, y_train, y_test = train_test_split(
    X_imputed, y,
    test_size=0.3, random_state=42, stratify=y
)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)


Outcome value counts (after mapping):
Outcome
0    500
1    268
Name: count, dtype: int64


## 8(a) Question – Is the Data Imbalanced?
> Is the Pima diabetes data imbalanced? What could be the problem of imbalanced data?

In [4]:
# 8(a) – Class distribution

print(y.value_counts())

Outcome
0    500
1    268
Name: count, dtype: int64


### 8(a) Explanation – Class Imbalance

The counts usually show more **non-diabetic** than **diabetic** cases. If one class is much more frequent than the
other, the dataset is **imbalanced**.

Problems of imbalanced data (from slides):
- A classifier that always predicts the majority class can have high **accuracy** but is useless for the minority
  class.
- Algorithms tend to be biased toward the majority class, giving low recall for the minority (important) class.
Thus, we need special methods or evaluation metrics for imbalanced data.

## 8(b) Question – Making the Data Balanced
> What can you do to make the data balanced? Explain your approach and implement it.

In [5]:
# 8(b) – Example: simple random oversampling of minority class (code placeholder)
# (In practice you can also use SMOTE as taught.)

from sklearn.utils import resample
import numpy as np

# Rebuild train DataFrame for oversampling
train_df = pd.concat(
    [pd.DataFrame(X_train, columns=X.columns).reset_index(drop=True),
     y_train.reset_index(drop=True)],
    axis=1
)

class0 = train_df[train_df['Outcome'] == 0]
class1 = train_df[train_df['Outcome'] == 1]

print("Class counts in training data:")
print(train_df['Outcome'].value_counts())

if len(class0) == 0 or len(class1) == 0:
    raise ValueError("Cannot oversample: one class has 0 samples in the training set.")

if len(class0) > len(class1):
    majority, minority = class0, class1
else:
    majority, minority = class1, class0

minority_upsampled = resample(
    minority,
    replace=True,
    n_samples=len(majority),
    random_state=42
)

train_bal = pd.concat([majority, minority_upsampled])
X_train_bal = train_bal.drop(columns=['Outcome'])
y_train_bal = train_bal['Outcome']

scaler_bal = StandardScaler()
X_train_bal_scaled = scaler_bal.fit_transform(X_train_bal)

print("\nOriginal train class distribution:")
print(y_train.value_counts())
print("\nBalanced train class distribution:")
print(y_train_bal.value_counts())


Class counts in training data:
Outcome
0    350
1    187
Name: count, dtype: int64

Original train class distribution:
Outcome
0    350
1    187
Name: count, dtype: int64

Balanced train class distribution:
Outcome
0    350
1    350
Name: count, dtype: int64


### 8(b) Explanation – Balancing Techniques

From the *Class Imbalance* slides, common techniques are:
- **Over-sampling** the minority class (e.g., duplicating or generating synthetic samples like SMOTE).
- **Under-sampling** the majority class.
- **Cost-sensitive learning** (assign higher cost to misclassifying minority).

Here we used a simple **random oversampling**:
- Randomly sample with replacement from the minority class until its size equals the majority class.
- This yields a balanced training set in terms of class counts.

## 8(c) Question – Prediction with and without Balancing
> Make predictions of Outcome using:
> 1. The original (imbalanced) training data.
> 2. The balanced data obtained in (b).
> Use all features and compare the results.

In [6]:
# 8(c) – Random forest on original vs balanced data

# Model on original data
rf_orig = RandomForestClassifier(n_estimators=200, random_state=42)
rf_orig.fit(X_train_scaled, y_train)
y_pred_orig = rf_orig.predict(X_test_scaled)
print("Original-data model:")
print(confusion_matrix(y_test, y_pred_orig))
print(classification_report(y_test, y_pred_orig))

# Model on balanced data
rf_bal = RandomForestClassifier(n_estimators=200, random_state=42)
rf_bal.fit(X_train_bal_scaled, y_train_bal)
y_pred_bal = rf_bal.predict(scaler_bal.transform(X_test))
print("Balanced-data model:")
print(confusion_matrix(y_test, y_pred_bal))
print(classification_report(y_test, y_pred_bal))

Original-data model:
[[129  21]
 [ 38  43]]
              precision    recall  f1-score   support

           0       0.77      0.86      0.81       150
           1       0.67      0.53      0.59        81

    accuracy                           0.74       231
   macro avg       0.72      0.70      0.70       231
weighted avg       0.74      0.74      0.74       231

Balanced-data model:
[[126  24]
 [ 40  41]]
              precision    recall  f1-score   support

           0       0.76      0.84      0.80       150
           1       0.63      0.51      0.56        81

    accuracy                           0.72       231
   macro avg       0.69      0.67      0.68       231
weighted avg       0.71      0.72      0.71       231



### 8(c) Explanation – Effect of Balancing

Comparing the confusion matrices and classification reports:
- The model trained on **original imbalanced** data may have higher overall accuracy but lower recall for diabetics.
- The model trained on **balanced** data tends to have improved **recall** and **F1-score** for the minority class,
  even if accuracy changes only slightly.

In imbalanced problems, improving detection of the minority class is usually more important than maximizing overall
accuracy.

## 8(d) Question – Check the Model on the Original Dataset
> Check also the model that you make in point (c) on the original dataset. What can you conclude?

In [7]:
# 8(d) – Evaluate balanced model on full dataset

rf_bal_all = RandomForestClassifier(n_estimators=200, random_state=42)
rf_bal_all.fit(X_train_bal_scaled, y_train_bal)

scaler_full = StandardScaler()
X_full_scaled = scaler_full.fit_transform(X)
y_pred_full = rf_bal_all.predict(scaler_full.transform(X))

print("Balanced model evaluated on full dataset:")
print(confusion_matrix(y, y_pred_full))
print(classification_report(y, y_pred_full))

Balanced model evaluated on full dataset:
[[439  61]
 [ 49 219]]
              precision    recall  f1-score   support

           0       0.90      0.88      0.89       500
           1       0.78      0.82      0.80       268

    accuracy                           0.86       768
   macro avg       0.84      0.85      0.84       768
weighted avg       0.86      0.86      0.86       768



### 8(d) Explanation – Overall Performance

Evaluating the balanced-data model on the whole dataset shows whether it generally detects more diabetic cases.
Often we see:
- Higher recall for the diabetic class than the model trained on imbalanced data.
- Some increase in false positives, which may be acceptable in medical screening.

Conclusion: balancing (over-sampling) can significantly improve the model’s usefulness for detecting the minority
class (diabetes).